stages:
  - test
  - release

unittest:
  stage: test
  image: golang:1.11.3-stretch
  only:
    - branches
  cache:
    paths:
      - .cache
  variables:
    GO111MODULE: "on"
  script:
    - mkdir -p .cache
    - export GOPATH="$CI_PROJECT_DIR/.cache"
    - go vet ./...
    # don't check mocks folder
    - go test -coverprofile=coverage.out $(go list ./... | grep -v /mocks)
    - go tool cover -func=coverage.out
  coverage: '/total:\s+\(statements\)\s+(\d+.\d+\%)/'

release-image:
  stage: release
  image: docker:18.03.1-ce
  only:
    - tags
  services:
    - docker:18.03.1-ce-dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
  before_script:
    - docker info
  script:
    - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
    - docker build -t chihkaiyu/gitlack:$CI_COMMIT_REF_NAME .
    - docker push chihkaiyu/gitlack:$CI_COMMIT_REF_NAME
    - docker logout